image: openjdk:8

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: therapi
  MYSQL_USER: therapi
  MYSQL_PASSWORD: therapie
  THERAPIHOME: ../Files/tests/resources



before_script:
  - apt-get update
  - update-alternatives --query java || true
  - ls -al /usr/bin/java || true
  - which java || true
  - ls -al /etc/alternatives/java || true
  - apt-get -y install ant
  - ls -al /etc/alternatives/java ||true
  - update-alternatives --query java || true
  

stages:
  - build
  - test
  - dist
  - deploy

ci_build:
  stage: build
  script:
    - cd Build
    - ant clean
    - ant build-all
  artifacts:
    paths:
      - ./*/bin
      - ./*/bin-tests
    expire_in: 1 week

ci_test:
  stage: test
  dependencies:
    - ci_build
  services:
    - mariadb
  script:
    - apt-get -y install mariadb-client
    - cat Files/sql/AlleTabellen.sql | mysql -u $MYSQL_USER -h mariadb --password="$MYSQL_PASSWORD" therapi
    - cd Build
    - ant JUnits
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - dist-tests/TEST-*.xml
      - dist-tests/*/TEST-*.xml
      - dist-tests/TEST-*.txt
      - dist-tests/*/TEST-*.txt
      - dist-tests/reports
    reports:
      junit: dist-tests/reports/TESTS-TestSuites.xml

pages:
  stage: deploy
  dependencies:
    - ci_test
  script:
    - mkdir -p public/
    - mv dist-tests/reports/html public/junit
    - cd Build
    - ant CoCo-all
    - cd ..
    - mv dist-test/reports/jacoco public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - entwicklung
      
ci_dist:
  stage: dist
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "entwicklung"'
      when: always
    - when: never
  script:
    - cd Build
    - ant dist
  artifacts:
    expire_in: 2 weeks
    when: on_success
    paths:
      - dist/*
