# The origibal image (installs openJDK-11 as dep of ant):
# image: openjdk:8
# Astrid found this image containing real Oracle-JDK-8:

image: tomsontom/oracle-java8-mvn:latest

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: therapi
  MYSQL_USER: therapi
  MYSQL_PASSWORD: therapie
  THERAPIHOME: ../Files/tests/resources



before_script:
  - apt-get update
  - update-alternatives --query java || true
  - ls -al /usr/bin/java || true
  - which java || true
  - ls -al /etc/alternatives/java || true
  - apt-get -y install ant zip
  - ls -al /etc/alternatives/java ||true
  - update-alternatives --query java || true
  

stages:
  - build
  - test
  - dist
  - deploy

ci_build:
  stage: build
  script:
    - cd Build
    - ant clean
    - ant build-all
  artifacts:
    paths:
      - ./*/bin
      - ./*/bin-tests
    expire_in: 1 week

ci_test:
  stage: test
  dependencies:
    - ci_build
  services:
    - mariadb
  script:
    - apt-get -y install mariadb-client
    - cat Files/sql/AlleTabellen.sql | mysql -u $MYSQL_USER -h mariadb --password="$MYSQL_PASSWORD" therapi
    - for sqlFile in Files/tests/resources/sql/*.sql;do cat "${sqlFile}" |mysql -u $MYSQL_USER -h mariadb --password="$MYSQL_PASSWORD" therapi ;done
    - cd Build
    - ant JUnits
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - dist-tests/TEST-*.xml
      - dist-tests/*/TEST-*.xml
      - dist-tests/TEST-*.txt
      - dist-tests/*/TEST-*.txt
      - dist-tests/reports
    reports:
      junit: dist-tests/reports/TESTS-TestSuites.xml

pages:
  stage: deploy
  dependencies:
    - ci_test
    - ci_dist
  script:
    - mkdir -p public/latest
    - mv dist-tests/reports/html public/junit
    - cd Build
    - ant CoCo-all
    - ant jars
    - ant copyfiles
    - ./make-latest-html.sh
    - cd ..
    - mv dist-tests/reports/jacoco public/
    - zip -9r latest-jars-nolibs.zip dist/*.jar dist/latest/latest.html
    - mv latest-jars-nolibs.zip public/latest
    - cp dist/latest/latest.html public/latest/index.html
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - entwicklung
      
ci_dist:
  stage: dist
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^WIP:'
      when: never
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "entwicklung"'
      when: always
    - when: never
  script:
    - cd Build
    - ant dist
  artifacts:
    expire_in: 2 weeks
    when: on_success
    paths:
      - dist/*
