image: openjdk:8

services:
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root

before_script:
  - apt-get update
  - update-alternatives --query java || true
  - ls -al /etc/alternatives/java
  - apt-get -y install ant
  - ls -al /etc/alternatives/java
  - update-alternatives --query java || true

stages:
  - build
  - test

ci_build:
  stage: build
  script:
    - cd Build
    - ant clean
    - ant

ci_test:
  stage: test
  script:
    - cd Build
    - ant clean dist

