image: openjdk:8

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: therapi
  MYSQL_USER: therapi
  MYSQL_PASSWORD: therapie

services:
  - mariadb

before_script:
  - apt-get update
  - update-alternatives --query java || true
  - ls -al /usr/bin/java || true
  - which java || true
  - ls -al /etc/alternatives/java || true
  - apt-get -y install ant
  - ls -al /etc/alternatives/java ||true
  - update-alternatives --query java || true

stages:
  - build
  - test

ci_build:
  stage: build
  script:
    - cd Build
    - ant clean
    - ant build-all
  artifacts:
    untracked: true
    expire_in: 1 week

ci_test:
  stage: test
  dependencies:
    - ci_build
  script:
    - cd Build
    - ant JUnits
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - dist-tests/TEST-*.xml
      - dist-tests/TEST-*.txt
    reports:
      junit: dist-tests/TEST-*.xml
