package org.therapi.reha.patient.verlauf;

import static org.junit.Assert.assertEquals;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;

import org.junit.Test;

import sql.DatenquellenFactory;

public class VerlaufgateTest {
    @Test
    public void testInsertVerlauf() throws Exception {
        DatenquellenFactory ds2 = new DatenquellenFactory("") {
            @Override
            public Connection createConnection() throws SQLException {
                return new DummyConnection() {
                    @Override
                    public Statement createStatement() throws SQLException {
                      return new DummyStatement() {
                           @Override
                        public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
                            String expectedsql = "INSERT INTO verlauf ( `patient_id`,  `therapist`,  `documentator`, `rezept_nr` , `documentedday`,  `dayofdocumentation`, `text`) VALUES (123,\"\",\"documentator\",\"rezeptnummer\",'2010-01-11','2020-02-21',\"text\");";
                            assertEquals(expectedsql, sql);
                            return super.execute(sql);
                        };
                       };

                    }
                };
            }

        };
        Verlauf verlauf = new Verlauf();
        verlauf.dayofDocumentation= LocalDate.of(2020, 2, 21);
        verlauf.documentator="documentator";
        verlauf.documentedDay=LocalDate.of(2010, 1, 11);
        verlauf.id=0; //unstored
        verlauf.patientID=123;
        verlauf.rezeptNr="rezeptnummer";
        verlauf.text="text";
                new Verlaufgate(ds2).insert(verlauf);
    }


}
