# This is a basic workflow to help you get started with Actions

name: Keep fork uptodate

on:
  schedule:
  - cron: "0 * * * *"

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: "false"

jobs:
  pull-remote:
    runs-on: ubuntu-latest

    steps:
    # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event.inputs.debug_enabled }}
        
      # Runs a set of commands using the runners shell
      - name: fetch and push
        run: |
            ls -la
